### ISSUE TITLE
Adding any modded item to "holdingItems" list in config file makes player extend both arms even when not holding anything

### ISSUE THREAD

**Issue by CerbTheOne** [tr7zw/NotEnoughAnimations#22] opened 2021-04-17 03:55 UTC
I tested it with multiple mods and the problem happened with all of them, so I'm guessing it isn't tied to any specific mod, but to modded items in general. I'm using the mod with forge.

This is how it looks when you aren't holding anything.
![image](https://user-images.githubusercontent.com/22283069/115100763-29d6ba80-9f15-11eb-8575-86ebb20c9355.png)

Holding one of the newly registered items makes the player lower one of the hands.
![image](https://user-images.githubusercontent.com/22283069/115100765-2e9b6e80-9f15-11eb-9180-93310c0f140f.png)

The hand also looks wrong in first person.
![image](https://user-images.githubusercontent.com/22283069/115100884-37407480-9f16-11eb-9bff-15fcf9101520.png)

I double-checked the grammar and the IDs and it's all good.
![image](https://user-images.githubusercontent.com/22283069/115100770-407d1180-9f15-11eb-9870-32467fad0605.png)

**Comment by tr7zw** [comment] 2021-04-19 11:50
Duplicate of #20

**Closed by tr7zw** 2021-04-19 11:50 UTC
