### ISSUE TITLE
First Person's arms not moving

### ISSUE THREAD

**Issue by Echo073** [tr7zw/NotEnoughAnimations#43] opened 2021-10-03 23:15 UTC
When in first person and **_not_** holding an item, the player's arms do not move when walking, punching or throwing out an item from the inventory. This is especially noticeable when shaders with shadows are enabled or when throwing out an item from the inventory when nothing is equipped in the main hand. (On 1.17.1 Fabric)

**Comment by tr7zw** [comment] 2021-10-06 22:38
Ok then this is teeeeechnically a duplicate of https://github.com/tr7zw/FirstPersonModel/issues/125 which teeeechnically should be here. Apparently while in first person the player model doesnt update correctly, causing the arms to behave this stiff. Will keep track of it here.

**Comment by tr7zw** [comment] 2021-10-13 16:22
OH MY GOD....
After nearly an hour I figured out why not having something in your hand while in first-person just breaks the arm smoothing...
The first "player" render call while in that state is the first-person hand, which always gets rendered with pitch 0 roll -0.1 and yaw 0. And since the arm smoothing should only be applied once each frame, it takes only these values(not the correct ones used after that), causing the arms to lock up. While having an item in your hand, the first-person hand is not rendered, bypassing this logic issue.

**Closed** 2021-10-13 16:26 UTC
