### ISSUE TITLE
Invalid dependency

### ISSUE THREAD

**Issue by seriousfreezing** [tr7zw/NotEnoughAnimations#230] opened 2024-12-09 22:10 UTC
![image](https://github.com/user-attachments/assets/fd414a68-9208-44ac-9b88-5b070098f6c3)

**Comment by tr7zw** [comment] 2024-12-09 22:11
That's TLauncher marked as incompatible cause I'm sick of the issues caused by the improperly cracked Minecraft. So this is fine and just auto-added by MCPublish.

**Closed by tr7zw** 2024-12-09 22:11 UTC
